### ISSUE TITLE
Error in constants file

### ISSUE THREAD

**Issue by jersonjunior** [kevinppaulo/rocketchat-whatsapp-integration#4]
I found error in importing constants, I think the right thing would be from import src.constants *, you saved the file in src / as constants.example.py instead of constants..py

**Comment by kevinppaulo** [comment]
Yes, I recently changed that file from constants.py to constants.example.py. I did it because that file is just an example. I should state in the readme.md file that this file must be renamed.

**Comment by kevinppaulo** [comment]
I sent you an email on jersonjunior@bsd.com.br with my contact info.
